baseURL = 'https://blueprint-website-48f38.web.app/'
languageCode = 'en-us'
title = 'UofA Blueprint'
disableKinds = ['taxonomy', 'term']

[params]
  currentProjects = [
    { header = "Bissell Centre", image = "images/projects/bissell-lg.png" },
    { header = "Alzheimer Society of Calgary", image = "images/projects/asc-lg.png" },
    { header = "Dish Zero", image = "images/projects/dish-zero-lg.png" }
  ]
