baseURL = 'https://example.org/'
languageCode = 'en-us'
title = 'UofA Blueprint'
disableKinds = ['taxonomy', 'term']

[params]
  currentProjects = [
    { header = "Bissell Centre", blurb = "", image = "" },
    { header = "Alzheimer Society of Calgary", blurb = "", image = "" },
    { header = "Internal Tools", blurb = "", image = "" }
  ]
